---
cidr_networks:
  management: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

global_overrides:
  external_lb_vip_address: 54.200.243.85
  internal_lb_vip_address: 35.94.177.14
  management_bridge: "br-mgmt"
  haproxy_keepalived_internal_interface: br-mgmt
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "management"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_management_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_openvswitch_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

shared-infra_hosts:
  controller-1:
    ip: 54.200.243.85
    ansible_user: ubuntu
  controller-2:
    ip: 35.94.177.14
    ansible_user: ubuntu
  controller-3:
    ip: 44.252.9.141
    ansible_user: ubuntu

compute_hosts:
  compute-1:
    ip: 54.245.199.112
    ansible_user: ubuntu
  compute-2:
    ip: 35.164.229.7
    ansible_user: ubuntu

storage_hosts:
  storage-1:
    ip: 35.87.100.53
    ansible_user: ubuntu
  storage-2:
    ip: 44.246.182.110
    ansible_user: ubuntu
  storage-3:
    ip: 35.163.60.85
    ansible_user: ubuntu

